-- MySQL Script generated by MySQL Workbench
-- Mon Feb  8 10:44:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_a6eeb5_dbhoppa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_a6eeb5_dbhoppa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_a6eeb5_dbhoppa` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_a6eeb5_dbhoppa` ;

-- -----------------------------------------------------
-- Table `db_a6eeb5_dbhoppa`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_a6eeb5_dbhoppa`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_a6eeb5_dbhoppa`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_a6eeb5_dbhoppa`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(75) NOT NULL,
  `email` VARCHAR(65) NOT NULL,
  `password` VARCHAR(95) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(75) NOT NULL,
  `fullName` VARCHAR(85) NULL DEFAULT NULL,
  `image_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_image1_idx` (`image_id` ASC) VISIBLE,
  INDEX `fk_users_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_image1`
    FOREIGN KEY (`image_id`)
    REFERENCES `db_a6eeb5_dbhoppa`.`image` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `db_a6eeb5_dbhoppa`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_a6eeb5_dbhoppa`.`qr_devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_a6eeb5_dbhoppa`.`qr_devices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` TINYINT NULL DEFAULT NULL,
  `latitude` VARCHAR(45) NULL DEFAULT NULL,
  `longitude` VARCHAR(45) NULL DEFAULT NULL,
  `qr_devicescol` VARCHAR(45) NULL DEFAULT NULL,
  `lastScan` DATETIME NULL DEFAULT NULL,
  `alerta` TINYINT NULL DEFAULT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_qr_devices_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_qr_devices_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `db_a6eeb5_dbhoppa`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_a6eeb5_dbhoppa`.`mascotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_a6eeb5_dbhoppa`.`mascotas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `raza` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `contacto` VARCHAR(115) NOT NULL,
  `users_id` INT NOT NULL,
  `image_id` INT NULL DEFAULT NULL,
  `qr_devices_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mascotas_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_mascotas_image1_idx` (`image_id` ASC) VISIBLE,
  INDEX `fk_mascotas_qr_devices1_idx` (`qr_devices_id` ASC) VISIBLE,
  CONSTRAINT `fk_mascotas_image1`
    FOREIGN KEY (`image_id`)
    REFERENCES `db_a6eeb5_dbhoppa`.`image` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mascotas_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `db_a6eeb5_dbhoppa`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_mascotas_qr_devices1`
    FOREIGN KEY (`qr_devices_id`)
    REFERENCES `db_a6eeb5_dbhoppa`.`qr_devices` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_a6eeb5_dbhoppa`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_a6eeb5_dbhoppa`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `ext` VARCHAR(45) NULL DEFAULT NULL,
  `url` VARCHAR(45) NOT NULL,
  `mascotas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_image_mascotas1_idx` (`mascotas_id` ASC) VISIBLE,
  CONSTRAINT `fk_image_mascotas1`
    FOREIGN KEY (`mascotas_id`)
    REFERENCES `db_a6eeb5_dbhoppa`.`mascotas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
